openapi: 3.0.3
info:
  title: Swagger Petstore Store service- OpenAPI 3.0
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://petstore3.swagger.io/api/v3
tags:
  - name: store
    description: Access to Petstore orders
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io
paths:
  /store/inventory:
    $ref: './operations/store-inventory.yml'
  /store/order:
    $ref: './operations/store-order.yml'
  /store/order/{orderId}:
    $ref: './operations/store-orderId.yml'

components:
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
